;/*=========== Constructor Fin Begin  ===========*/		
{"cannon emplacement_small_deep_mortar_50mm_krh38"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_small_deep_mortar_50mm_krh38" "basis")
	}
}
{"cannon emplacement_ground_floor_20mm_itk35"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_ground_floor_20mm_itk35" "basis")
	}
}
;{"emplacement_middle_plank_75mm_itk37"
	;{on "dig_in"  overload 
		;("cannon_sandbag" args "emplacement_middle_plank_75mm_itk37" "basis")
	;}
;}
{"emplacement_ground_floor_75mm_itk37"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_ground_floor_75mm_itk37" "basis")
	}
}
;/*=========== Constructor Fin End  ===========*/		
;/*============================================ Constructor Generic Begin  ============================================*/	
;/*=========== Emplacement_cannon Begin ===========*/	
{"emplacement_ground_floor_aa_small_low"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_ground_floor_aa_small_low" "basis")
	}
}
{"emplacement_ground_floor_aa_small"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_ground_floor_aa_small" "basis")
	}
}
{"emplacement_ground_floor_aa_low"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_ground_floor_aa_low" "basis")
	}
}
{"emplacement_ground_floor_aa"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_ground_floor_aa" "basis")
	}
}
{"emplacement_ground_floor_aa_tall"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_ground_floor_aa_tall" "basis")
	}
}
{"emplacement_ground_floor_aa_middle_tall"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_ground_floor_aa_middle_tall" "basis")
	}
}
{"emplacement_ground_floor_aa_large"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_ground_floor_aa_large" "basis")
	}
}
{"emplacement_light_atgun"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_light_atgun" "basis")
	}
}
{"emplacement_light_mortar"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_middle_mortar_set" "basis")
		;("cannon_sandbag" args "emplacement_light_mortar" "basis")
	}
}
{"emplacement_light_inf_crate"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_light_inf_crate" "basis")
	}
}
{"emplacement_middle_log_mortar"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_middle_log_mortar" "basis")
	}
}
{"emplacement_middle_atgun"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_middle_atgun" "basis")
	}
}
{"emplacement_middle_log_fieldgun"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_middle_log_fieldgun" "basis")
	}
}
{"emplacement_middle_mortar"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_middle_mortar_set" "basis")
	}
}
{"emplacement_middle_log_rocket"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_middle_log_rocket" "basis")
	}
}
{"emplacement_middle_log_rocket_tall"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_middle_log_rocket_tall" "basis")
	}
}

{"emplacement_middle_log_atgun"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_middle_log_atgun" "basis")
	}
}
{"emplacement_middle_log_heavy_anti_air"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_middle_log_heavy_anti_air" "basis")
	}
}

{"emplacement_artillery_middle"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_artillery_middle" "basis")
	}
}
{"emplacement_artillery_heavy"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_artillery_heavy" "basis")
	}
}
;/*=========== Emplacement_cannon End ===========*/		


;/*============================================ Constructor Generic End  ============================================*/		
;/*============================================ Constructor Ger Begin  ============================================*/		
{"emplacement_small_mgun_lafette"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_small_mgun_lafette" "basis")
		;{spawn "emplacement_small_mgun_lafette" offset 5 3 0 }
		;{call "deactivate_vehicle"}
		;{start_sound "vehicle/deploy/foxhole"}
		;{delay 5
			;{start_sound "vehicle/construction/entrench"}
			;{spawn "emplacement_small_mgun_lafette" offset 4 5 0 }
			;{call "activate_vehicle"}
		;}
	}
}
{"emplacement_small_75mm_lg40"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_small_75mm_lg40" "basis")
	}
}
{"emplacement_ground_floor_37mm_flak37"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_ground_floor_37mm_flak37" "basis")
	}
}
{"emplacement_light_atgun_47mm_pakt"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_light_atgun_47mm_pakt" "basis")
	}
}

{"emplacement_ground_floor_50mm_flak41"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_ground_floor_50mm_flak41" "basis")
	}
}
{"emplacement_middle_log_howitzer_105mm_lefh18"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_middle_log_howitzer_105mm_lefh18" "basis")
	}
}
{"panzernest_krab"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "panzernest_krab_sandbag_stage" "basis")
	}
}
;/*============================================ Constructor Ger End  ============================================*/		
;/*============================================ Constructor Rus Begin  ============================================*/	

{"emplacement_ground_floor_maxim"
	{on "dig_in"  overload
		("cannon_sandbag" args "emplacement_ground_floor_maxim" "basis")
	}
}
{"emplacement_ground_floor_ds39_stand"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_ground_floor_ds39_stand" "basis")
	}
}
{"emplacement_ground_floor_dshk_aa"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		{if terrain_fx "bunker_floor"
			("cannon_sandbag" args "emplacement_ground_floor_dshk_aa_bunker_floor" "basis")
		else
			("cannon_sandbag" args "emplacement_ground_floor_dshk_aa" "basis")
		}
	}
}
{"emplacement_small_ds39_stand"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_small_ds39_stand" "basis")
	}
}
{"emplacement_small_mgun_maxim"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_small_mgun_maxim" "basis")
	}
}
{"emplacement_small_deep_mgun_maxim"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_small_deep_mgun_maxim" "basis")
	}
}
{"emplacement_small_deep_dshk_aa"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_small_deep_dshk_aa" "basis")
	}
}
{"emplacement_ground_floor_dshk"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_ground_floor_dshk" "basis")
	}
}
{"emplacement_ground_floor_25mm_72k"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_ground_floor_25mm_72k" "basis")
	}
}
{"emplacement_ground_floor_37mm_61k"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_ground_floor_37mm_61k" "basis")
	}
}
{"emplacement_light_atgun_rus"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_light_atgun_rus" "basis")
	}
}
{"emplacement_middle_log_rocket_rus"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_middle_log_rocket_rus" "basis")
	}
}
{"emplacement_middle_log_howitzer_122mm_m30"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_middle_log_howitzer_122mm_m30" "basis")
	}
}
;/*============================================ Constructor Rus End  ============================================*/	
;/*============================================ Constructor USA Begin  ============================================*/	
{"emplacement_ground_floor_tripod"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_ground_floor_tripod" "basis")
	}
}
{"emplacement_small_deep_mortar"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_small_deep_mortar" "basis")
	}
}
{"emplacement_ground_floor_90mm_m1a1"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_ground_floor_90mm_m1a1" "basis")
	}
}
{"emplacement_ground_floor_50cal_quad_m45"
	{on "dig_in"  overload
		{if terrain_fx "bunker_floor"
			("cannon_sandbag" args "emplacement_ground_floor_50cal_quad_m45_bunker_floor" "basis")
		else
			("cannon_sandbag" args "emplacement_ground_floor_50cal_quad_m45" "basis")
		}
	}
}
{"emplacement_ground_floor_40mm_m1"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_ground_floor_40mm_m1" "basis")
	}
}
{"emplacement_90mm_m1a1_sandbag_set"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_90mm_m1a1_sandbag_set" "basis")
	}
}
{"emplacement_middle_log_howitzer_105mm_m2a1"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_middle_log_howitzer_105mm_m2a1" "basis")
	}
}

;/*============================================ Constructor USA End  ============================================*/			


