;/*============================================ Constructor Generic begin  ============================================*/		
;/*=========== Emplacement_tank Begin ===========*/	
{"emplacement_tank_trench_light"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_tank_trench_light" "basis")
	}
}
{"emplacement_tank_trench_middle"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_tank_trench_middle" "basis")
	}
}
{"emplacement_tank_trench_heavy"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_tank_trench_heavy" "basis")
	}
}
{"emplacement_tank_trench_assault_gun"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_tank_trench_assault_gun" "basis")
	}
}

;/*=========== Emplacement_tank end ===========*/	
;/*=========== Emplacement_car Begin ===========*/	
{"emplacement_motor"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_motor" "basis")
	}
}
{"emplacement_jeep_trench"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_jeep_trench" "basis")
	}
}
{"emplacement_jeep_trench_tall"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_jeep_trench_tall" "basis")
	}
}
{"emplacement_halftrack_trench_low"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_halftrack_trench_low" "basis")
	}
}
{"emplacement_halftrack_trench"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_halftrack_trench" "basis")
	}
}
{"emplacement_halftrack_trench_tall"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_halftrack_trench_tall" "basis")
	}
}
{"emplacement_halftrack_trench_reversed_low"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_halftrack_trench_reversed_low" "basis")
	}
}
{"emplacement_halftrack_trench_reversed_tall"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_halftrack_trench_reversed_tall" "basis")
	}
}
;/*=========== Emplacement_car end ===========*/
;/*============================================ Constructor Generic End  ============================================*/		
;/*============================================ Constructor Ger Begin  ============================================*/		
;/*=========== Emplacement_tank Begin ===========*/	
{"emplacement_tank_trench_panzer1f"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_tank_trench_panzer1f" "basis")
	}
}
{"emplacement_tank_trench_stug3"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_tank_trench_stug3" "basis")
	}
}
{"emplacement_tank_trench_stug3g"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_tank_trench_stug3g" "basis")
	}
}
{"emplacement_tank_trench_jagdpanzer4"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_tank_trench_jagdpanzer4" "basis")
	}
}
{"emplacement_tank_trench_panzer5"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_tank_trench_panzer5" "basis")
	}
}
{"emplacement_tank_trench_jagdpanther"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_tank_trench_jagdpanther" "basis")
	}
}
{"emplacement_tank_trench_tiger2"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_tank_trench_tiger2" "basis")
	}
}
{"emplacement_tank_trench_ferdinand"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_tank_trench_ferdinand" "basis")
	}
}
;{"emplacement_tank_trench_jagdtiger"
	;{on "dig_in"  overload 
		;("cannon_sandbag" args "emplacement_tank_trench_jagdtiger" "basis")
	;}
;}
;/*=========== Emplacement_tank end ===========*/	
;/*=========== Emplacement_car Begin ===========*/	
{"emplacement_bmw_r71"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_bmw_r71" "basis")
	}
}
;{"emplacement_kubelwagen_mg_trench"
	;{on "dig_in"  overload 
		;("cannon_sandbag" args "emplacement_kubelwagen_mg_trench" "basis")
	;}
;}
;{"emplacement_kfz15_trench"
	;{on "dig_in"  overload 
		;("cannon_sandbag" args "emplacement_kfz15_trench" "basis")
	;}
;}
{"emplacement_kfz13_trench"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_kfz13_trench" "basis")
	}
}
;/*=========== Emplacement_car end ===========*/
;/*============================================ Constructor Ger End  ============================================*/		
;/*============================================ Constructor Rus Begin  ============================================*/	
;/*=========== Emplacement_tank Begin ===========*/	
{"emplacement_tank_trench_t20"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_tank_trench_t20" "basis")
	}
}
{"emplacement_tank_trench_bt"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_tank_trench_bt" "basis")
	}
}
{"emplacement_tank_trench_t34"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_tank_trench_t34" "basis")
	}
}
{"emplacement_tank_trench_t3485"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_tank_trench_t3485" "basis")
	}
}
{"emplacement_tank_trench_su85"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_tank_trench_su85" "basis")
	}
}
{"emplacement_tank_trench_kv1"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_tank_trench_kv1" "basis")
	}
}
{"emplacement_tank_trench_kv2"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_tank_trench_kv2" "basis")
	}
}
{"emplacement_tank_trench_is2"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_tank_trench_is2" "basis")
	}
}
{"emplacement_tank_trench_is2_45"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_tank_trench_is2_45" "basis")
	}
}
{"emplacement_tank_trench_isu"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_tank_trench_isu" "basis")
	}
}
;{"emplacement_tank_trench_su100y"
	;{on "dig_in"  overload 
		;("cannon_sandbag" args "emplacement_tank_trench_su100y" "basis")
	;}
;}
;/*=========== Emplacement_tank end ===========*/	
;/*=========== Emplacement_car Begin ===========*/	

;/*=========== Emplacement_car end ===========*/
;/*============================================ Constructor Rus End  ============================================*/	
;/*============================================ Constructor USA Begin  ============================================*/	
;/*=========== Emplacement_tank Begin ===========*/	
{"emplacement_tank_trench_stuart"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_tank_trench_stuart" "basis")
	}
}	
{"emplacement_tank_trench_m24_chaffee"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_tank_trench_m24_chaffee" "basis")
	}
}	
{"emplacement_tank_trench_m4"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_tank_trench_m4" "basis")
	}
}
{"emplacement_tank_trench_m26"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_tank_trench_m26" "basis")
	}
}
;/*=========== Emplacement_tank end ===========*/			
;/*=========== Emplacement_car Begin ===========*/	
;{"emplacement_willys_mg_trench"
	;{on "dig_in"  overload 
		;("cannon_sandbag" args "emplacement_willys_mg_trench" "basis")
	;}
;}
{"emplacement_wc52_50cal_trench"
	{on "dig_in"  overload 
		{link_sound "deploy"		"vehicle/construction/wood_deploy"}
		{play_sound "deploy"}
		("cannon_sandbag" args "emplacement_wc52_50cal_trench" "basis")
	}
}
;{"emplacement_m6_gmc_trench"
	;{on "dig_in"  overload 
		;{call "emplacement_m6_gmc_trench"}
	;}
;}

;{"emplacement_halftrack_trench_m16_mgmc"
	;{on "dig_in"  overload 
		;{call "emplacement_halftrack_trench_m16_mgmc"}
	;}
;}
;/*=========== Emplacement_car end ===========*/