
; Presets for usa engineer Fortification skills

;/* - Fortification Building Skills - */
;=============================================================light=============================================================================
;/* - Fortification_engineer_light_usa_Skills begin - */
;================Emplacement_cover================
;/* - Fortification_Cover_Skills begin - */		
(define "engineer_light_usa"
	{fortification}
	{barricade
		{"fortifications" "barricade_sq"}
		{"fortifications" "barricade"}
		{"fortifications" "barbwire"}
		{"fortifications" "hedgehog"}
		{"fortifications" "foxhole_big"}
		{"fortifications" "tank_cover"}
	
		{"fortifications" "heavy_mg_mg34"}
		{"fortifications" "heavy_mg_maxim"}
	
		{"fortifications" "placement_nest"}
		{"fortifications" "pillbox_earth"}
		{"fortifications" "watch_tower"}
		{"fortifications" "sandbag_watchtower"}

		{"fortifications" "mortar_pit"}
		{"fortifications" "trench_modular"}	
		{"fortifications" "sandbag_heap_curved"}		
		{"fortifications" "sandbag_framed_straight_mod"}
		{"fortifications" "sandbag_framed_curved"}
		{"fortifications" "bush_cover"}

;/* - Fortification_Cover_Skills end - */	
;================Emplacement_cover================
;================Emplacement_Building================
;/* - Fortification_Building_Skills begin - */	

        {"fortifications" "usa_m2_30cal_foxhole"}
        {"fortifications" "usa_37mm_m3a1_emplacement"}
        {"fortifications" "usa_60mm_m2_foxhole"}	
        {"fortifications" "usa_75mm_m1a1_emplacement"}

;/* - Fortification_Building_Skills EnD - */	
;================Emplacement_Building================
;================Emplacement_Vehicle================	
;/* - Fortification_Vehicle_Skills begin - */	
	
	    {"fortifications" "usa_emplacement_bunker_national_guard"}
		{"fortifications" "usa_emplacement_bunker_national_guard_unlimited"}
		{"fortifications" "usa_emplacement_watch_tower"}		
		{"fortifications" "usa_emplacement_m2_30cal"}
		{"fortifications" "usa_emplacement_37mm_m3a1"}
		
		{"fortifications" "usa_emplacement_60mm_m2"}	
		{"fortifications" "usa_emplacement_small_75mm_m1a1"}
		
		


;/* - Fortification_Vehicle_Skills EnD - */	
;================Emplacement_Vehicle================


	}
	{"resources" "1000%"}
	{"resources_regeneration" "50%"}
	{mechanic factor 10.0}
)
;/* - Fortification_engineer_light_usa_Skills end - */	
;=============================================================middle=============================================================================
;/* - Fortification_engineer_usa_Skills begin - */	
;================Emplacement_cover================
;/* - Fortification_Cover_Skills begin - */	

(define "engineer_usa"
	{fortification}
	{barricade
		{"fortifications" "barricade_sq"}
		{"fortifications" "barricade"}
		{"fortifications" "barbwire"}
		{"fortifications" "hedgehog"}
		{"fortifications" "foxhole_big"}
		{"fortifications" "tank_cover"}
	
		{"fortifications" "heavy_mg_mg34"}
		{"fortifications" "heavy_mg_maxim"}
	
		{"fortifications" "placement_nest"}
		{"fortifications" "pillbox_earth"}
		{"fortifications" "watch_tower"}
		{"fortifications" "sandbag_watchtower"}

		{"fortifications" "mortar_pit"}
		{"fortifications" "trench_modular"}	
		{"fortifications" "sandbag_heap_curved"}		
		{"fortifications" "sandbag_framed_straight_mod"}
		{"fortifications" "sandbag_framed_curved"}
		{"fortifications" "bush_cover"}	
		
	
;/* - Fortification_Cover_Skills end - */	
;================Emplacement_cover================	
;================Emplacement_Building================		
;/* - Fortification_Building_Skills begin - */	


        {"fortifications" "usa_tower_m2_30cal"}
        {"fortifications" "usa_40mm_m1_emplacement"}
        {"fortifications" "usa_57mm_m1_emplacement"}	
        {"fortifications" "usa_75mm_m3a3_emplacement"}	
        {"fortifications" "usa_81mm_m1_mortar_position"}
		
			

;/* - Fortification_Building_Skills EnD - */	
;================Emplacement_Building================
;================Emplacement_Vehicle================
;/* - Fortification_Vehicle_Skills begin - */	
		{"fortifications" "usa_emplacement_watch_tower"}
		{"fortifications" "usa_emplacement_m2_30cal"}
        {"fortifications" "usa_emplacement_m2_50cal"}		
		{"fortifications" "usa_emplacement_m2_50cal_aa"}			
		
        {"fortifications" "usa_emplacement_40mm_m1"}	
		{"fortifications" "usa_emplacement_90mm_m1a1"}	
		
		{"fortifications" "usa_emplacement_37mm_m3a1"}			
		{"fortifications" "usa_emplacement_57mm_m1"}
		{"fortifications" "usa_emplacement_76mm_m5_m1"}
		{"fortifications" "usa_emplacement_76mm_m5_m6"}	

		{"fortifications" "usa_emplacement_60mm_m2"}
		{"fortifications" "usa_emplacement_81mm_m1"}
		{"fortifications" "usa_emplacement_107mm_m2"}
		
		{"fortifications" "usa_emplacement_75mm_m1a1"}
		{"fortifications" "usa_emplacement_75mm_m3a3"}	
		{"fortifications" "usa_emplacement_small_75mm_m1a1"}
		
		{"fortifications" "usa_emplacement_105mm_m2a1"}	

		{"fortifications" "usa_emplacement_bunker_national_guard"}
		{"fortifications" "usa_emplacement_bunker_national_guard_unlimited"}
;/* - Fortification_Vehicle_Skills EnD - */	
;================Emplacement_Vehicle================				

	}
	{"resources" "1000%"}
	{"resources_regeneration" "50%"}
	{mechanic factor 10.0}
)
;/* - Fortification_engineer_usa_Skills EnD - */	
;=============================================================heavy=============================================================================
;/* - Fortification_engineer_heavy_usa_Skills begin - */
;================Emplacement_cover================
;/* - Fortification_Cover_Skills begin - */	
(define "engineer_heavy_usa"
	{fortification}
	{barricade
		{"fortifications" "barricade_sq"}
		{"fortifications" "barricade"}
		{"fortifications" "barbwire"}
		{"fortifications" "hedgehog"}
		{"fortifications" "foxhole_big"}
		{"fortifications" "tank_cover"}
	
		{"fortifications" "heavy_mg_mg34"}
		{"fortifications" "heavy_mg_maxim"}
	
		{"fortifications" "placement_nest"}
		{"fortifications" "pillbox_earth"}
		{"fortifications" "watch_tower"}
		{"fortifications" "sandbag_watchtower"}

		{"fortifications" "mortar_pit"}
		{"fortifications" "trench_modular"}	
		{"fortifications" "sandbag_heap_curved"}		
		{"fortifications" "sandbag_framed_straight_mod"}
		{"fortifications" "sandbag_framed_curved"}
		{"fortifications" "bush_cover"}	


;/* - Fortification_Cover_Skills end - */	
;================Emplacement_cover================	
;================Emplacement_Building================		
;/* - Fortification_Building_Skills begin - */	

		
        {"fortifications" "usa_bunker_m2_50cal"}	
        {"fortifications" "usa_trench_pillbox_m2_50cal"}
        {"fortifications" "usa_76mm_m5_emplacement"}
        {"fortifications" "usa_90mm_m1a1_emplacement"}
        {"fortifications" "usa_105mm_m2a1_emplacement"}
        {"fortifications" "usa_107mm_m2_mortar_position"}	


;/* - Fortification_Building_Skills EnD - */	
;================Emplacement_Building================
;================Emplacement_Vehicle================
;/* - Fortification_Vehicle_Skills begin - */		
		{"fortifications" "usa_emplacement_bunker_national_guard"}
		{"fortifications" "usa_emplacement_bunker_national_guard_unlimited"}
		{"fortifications" "usa_emplacement_watch_tower"}		

		{"fortifications" "usa_emplacement_76mm_m5_m1"}
		{"fortifications" "usa_emplacement_76mm_m5_m6"}	
		{"fortifications" "usa_emplacement_90mm_m1a1"}
		{"fortifications" "usa_emplacement_107mm_m2"}		
		{"fortifications" "usa_emplacement_105mm_m2a1"}	
			

;/* - Fortification_Vehicle_Skills EnD - */	
;================Emplacement_Vehicle================	

	}
	{"resources" "1000%"}
	{"resources_regeneration" "50%"}
	{mechanic factor 10.0}
)
;/* - Fortification_engineer_heavy_usa_Skills end - */