
; Presets for rus engineer Fortification skills

;/* - Fortification Building Skills - */
;=============================================================light=============================================================================
;/* - Fortification_engineer_light_rus_Skills begin - */
;================Emplacement_cover================
;/* - Fortification_Cover_Skills begin - */		
(define "engineer_light_rus"
	{fortification}
	{barricade
		{"fortifications" "barricade_sq"}
		{"fortifications" "barricade"}
		{"fortifications" "barbwire"}
		{"fortifications" "hedgehog"}
		{"fortifications" "foxhole_big"}
		{"fortifications" "tank_cover"}
	
		{"fortifications" "heavy_mg_mg34"}
		{"fortifications" "heavy_mg_maxim"}
	
		{"fortifications" "placement_nest"}
		{"fortifications" "pillbox_earth"}
		{"fortifications" "watch_tower"}
		{"fortifications" "sandbag_watchtower"}

		{"fortifications" "mortar_pit"}
		{"fortifications" "trench_modular"}	
		{"fortifications" "sandbag_heap_curved"}		
		{"fortifications" "sandbag_framed_straight_mod"}
		{"fortifications" "sandbag_framed_curved"}
		{"fortifications" "bush_cover"}

;/* - Fortification_Cover_Skills end - */	
;================Emplacement_cover================
;================Emplacement_Building================
;/* - Fortification_Building_Skills begin - */
		
        {"fortifications" "rus_maxim_foxhole"}
        {"fortifications" "rus_25mm_72k_emplacement"}
        {"fortifications" "rus_45mm_m42_emplacement"}
		{"fortifications" "rus_76mm_bpk76_foxhole"}
		{"fortifications" "rus_76mm_m43_emplacement"}
		
;/* - Fortification_Building_Skills EnD - */	
;================Emplacement_Building================
;================Emplacement_Vehicle================	
;/* - Fortification_Vehicle_Skills begin - */	

		{"fortifications" "rus_emplacement_bunker_conscript"}	
		{"fortifications" "rus_emplacement_bunker_border"}

		{"fortifications" "rus_emplacement_watch_tower"}
		{"fortifications" "rus_emplacement_maxim"}	
		{"fortifications" "rus_emplacement_ds39"}
		{"fortifications" "rus_emplacement_sg43"}	
	
		
		{"fortifications" "rus_emplacement_25mm_72k"}
		{"fortifications" "rus_emplacement_45mm_m37"}	
		{"fortifications" "rus_emplacement_45mm_m42"}

		{"fortifications" "rus_emplacement_small_76mm_m43"}	

;/* - Fortification_Vehicle_Skills EnD - */	
;================Emplacement_Vehicle================


	}
	{"resources" "1000%"}
	{"resources_regeneration" "50%"}
	{mechanic factor 10.0}
)
;/* - Fortification_engineer_light_rus_Skills end - */	
;=============================================================middle=============================================================================
;/* - Fortification_engineer_rus_Skills begin - */	
;================Emplacement_cover================
;/* - Fortification_Cover_Skills begin - */	

(define "engineer_rus"


	{fortification}
	{barricade
		{"fortifications" "barricade_sq"}
		{"fortifications" "barricade"}
		{"fortifications" "barbwire"}
		{"fortifications" "hedgehog"}
		{"fortifications" "foxhole_big"}
		{"fortifications" "tank_cover"}
	
		{"fortifications" "heavy_mg_mg34"}
		{"fortifications" "heavy_mg_maxim"}
	
		{"fortifications" "placement_nest"}
		{"fortifications" "pillbox_earth"}
		{"fortifications" "watch_tower"}
		{"fortifications" "sandbag_watchtower"}

		{"fortifications" "mortar_pit"}
		{"fortifications" "trench_modular"}	
		{"fortifications" "sandbag_heap_curved"}		
		{"fortifications" "sandbag_framed_straight_mod"}
		{"fortifications" "sandbag_framed_curved"}
		{"fortifications" "bush_cover"}	
		
		
;/* - Fortification_Cover_Skills end - */	
;================Emplacement_cover================	
;================Emplacement_Building================		
;/* - Fortification_Building_Skills begin - */	
		
		{"fortifications" "rus_tower_maxim"}	
        {"fortifications" "rus_37mm_61k_emplacement"}
        {"fortifications" "rus_76mm_zis3_emplacement"}
        {"fortifications" "rus_76mm_m1927_emplacement"}
		{"fortifications" "rus_82mm_bm37_mortar_position"}

		
;/* - Fortification_Building_Skills EnD - */	
;================Emplacement_Building================
;================Emplacement_Vehicle================
;/* - Fortification_Vehicle_Skills begin - */	

		{"fortifications" "rus_emplacement_watch_tower"}
		{"fortifications" "rus_emplacement_maxim"}	
		{"fortifications" "rus_emplacement_ds39"}
		{"fortifications" "rus_emplacement_pillbox_sg43"}
		{"fortifications" "rus_emplacement_sg43"}	
		{"fortifications" "rus_emplacement_dshk"}	
		{"fortifications" "rus_emplacement_dshk_aa"}		
		
		{"fortifications" "rus_emplacement_25mm_72k"}
		{"fortifications" "rus_emplacement_37mm_61k"}			
		{"fortifications" "rus_emplacement_76mm_m1938"}	
        {"fortifications" "rus_emplacement_85mm_52k"}	
	
		{"fortifications" "rus_emplacement_45mm_m37"}	
		{"fortifications" "rus_emplacement_45mm_m42"}
		{"fortifications" "rus_emplacement_57mm_zis2"}
		{"fortifications" "rus_emplacement_76mm_zis3"}		
		{"fortifications" "rus_emplacement_100mm_bs3"}	

		{"fortifications" "rus_emplacement_76mm_m1927"}
		{"fortifications" "rus_emplacement_76mm_m43"}	
		{"fortifications" "rus_emplacement_small_76mm_m43"}	
	
		{"fortifications" "rus_emplacement_82mm_bm37"}			
		{"fortifications" "rus_emplacement_120mm_pm38"}
		
		{"fortifications" "rus_emplacement_122mm_m30"}

		{"fortifications" "rus_emplacement_bunker_border"}
		{"fortifications" "rus_emplacement_bunker_border_unlimited"}
		
		{"fortifications" "rus_emplacement_bunker_conscript"}
		{"fortifications" "rus_emplacement_bunker_conscript_unlimited"}
;/* - Fortification_Vehicle_Skills EnD - */	
;================Emplacement_Vehicle================	

	
	}
	{"resources" "1000%"}
	{"resources_regeneration" "50%"}
	{mechanic factor 10.0}
)
;/* - Fortification_engineer_rus_Skills EnD - */	
;=============================================================heavy=============================================================================
;/* - Fortification_engineer_heavy_rus_Skills begin - */
;================Emplacement_cover================
;/* - Fortification_Cover_Skills begin - */	
(define "engineer_heavy_rus"
	{fortification}
		{barricade
		{"fortifications" "barricade_sq"}
		{"fortifications" "barricade"}
		{"fortifications" "barbwire"}
		{"fortifications" "hedgehog"}
		{"fortifications" "foxhole_big"}
		{"fortifications" "tank_cover"}
	
		{"fortifications" "heavy_mg_mg34"}
		{"fortifications" "heavy_mg_maxim"}
	
		{"fortifications" "placement_nest"}
		{"fortifications" "pillbox_earth"}
		{"fortifications" "watch_tower"}
		{"fortifications" "sandbag_watchtower"}

		{"fortifications" "mortar_pit"}
		{"fortifications" "trench_modular"}	
		{"fortifications" "sandbag_heap_curved"}		
		{"fortifications" "sandbag_framed_straight_mod"}
		{"fortifications" "sandbag_framed_curved"}
		{"fortifications" "bush_cover"}	
		
		
;/* - Fortification_Cover_Skills end - */	
;================Emplacement_cover================	
;================Emplacement_Building================		
;/* - Fortification_Building_Skills begin - */	

		
        {"fortifications" "rus_bunker_maxim"}
        {"fortifications" "rus_bunker_ds39"}
		{"fortifications" "rus_bunker_dshk"}
		{"fortifications" "rus_pillbox_earth_dshk"}
        {"fortifications" "rus_85mm_gun"}			
        {"fortifications" "rus_100mm_bs3_emplacement"}
        {"fortifications" "rus_120mm_pm38_emplacement"}
		{"fortifications" "rus_122mm_m30_emplacement"}		
		
;/* - Fortification_Building_Skills EnD - */	
;================Emplacement_Building================
;================Emplacement_Vehicle================
;/* - Fortification_Vehicle_Skills begin - */		
		{"fortifications" "rus_emplacement_bunker_border"}
		{"fortifications" "rus_emplacement_bunker_border_unlimited"}
		
		{"fortifications" "rus_emplacement_bunker_conscript"}
		{"fortifications" "rus_emplacement_bunker_conscript_unlimited"}

		{"fortifications" "rus_emplacement_watch_tower"}

		{"fortifications" "rus_emplacement_85mm_52k"}		
		{"fortifications" "rus_emplacement_100mm_bs3"}		
		{"fortifications" "rus_emplacement_120mm_pm38"}
		{"fortifications" "rus_emplacement_122mm_m30"}
		
		
;/* - Fortification_Vehicle_Skills EnD - */	
;================Emplacement_Vehicle================	


	}
	{"resources" "1000%"}
	{"resources_regeneration" "50%"}
	{mechanic factor 10.0}
)
;/* - Fortification_engineer_heavy_rus_Skills end - */

