; Presets for fin engineer Fortification skills

;/* - Fortification Building Skills - */
;=============================================================;/* - Fortification_engineer_light_fin_Skills begin - */=============================================================================

;================Emplacement_cover================
;/* - Fortification_Cover_Skills begin - */		
(define "engineer_light_fin"
	{fortification}
	{barricade
		{"fortifications" "barricade_sq"}
		{"fortifications" "barricade"}
		{"fortifications" "barbwire"}
		{"fortifications" "hedgehog"}
		{"fortifications" "foxhole_big"}
		{"fortifications" "tank_cover"}
	
		{"fortifications" "heavy_mg_mg34"}
		{"fortifications" "heavy_mg_maxim"}
		{"fortifications" "heavy_mg_maxim_m1910_30"}
	
		{"fortifications" "placement_nest"}
		{"fortifications" "pillbox_earth"}
		{"fortifications" "watch_tower"}
		{"fortifications" "sandbag_watchtower"}

		{"fortifications" "mortar_pit"}
		{"fortifications" "trench_modular"}	
		{"fortifications" "sandbag_heap_curved"}		
		{"fortifications" "sandbag_framed_straight_mod"}
		{"fortifications" "sandbag_framed_curved"}
		{"fortifications" "bush_cover"}
		

;/* - Fortification_Cover_Skills end - */	
;================Emplacement_cover================
;================Emplacement_Building================
;/* - Fortification_Building_Skills begin - */	

		{"fortifications" "fin_maxim_foxhole"}
		{"fortifications" "fin_20mm_l39_position"}
		{"fortifications" "fin_20mm_itk40_emplacement"}
		{"fortifications" "fin_37mm_pstk36_emplacement"}
		{"fortifications" "fin_50mm_krh38_foxhole"}

;/* - Fortification_Building_Skills EnD - */	
;================Emplacement_Building================
;================Emplacement_Vehicle================	
;/* - Fortification_Vehicle_Skills begin - */	

;/* - Fortification_Vehicle_Skills EnD - */	
;================Emplacement_Vehicle================


	}
	{"resources" "1000%"}
	{"resources_regeneration" "50%"}
	{mechanic factor 10.0}
)

;=============================================================;/* - Fortification_engineer_light_fin_Skills end - */=============================================================================
;=============================================================;/* - Fortification_engineer_fin_Skills begin - */=============================================================================

;================Emplacement_cover================
;/* - Fortification_Cover_Skills begin - */	
(define "engineer_fin"
	{fortification}
	{barricade
		{"fortifications" "barricade_sq"}
		{"fortifications" "barricade"}
		{"fortifications" "barbwire"}
		{"fortifications" "hedgehog"}
		{"fortifications" "foxhole_big"}
		{"fortifications" "tank_cover"}
	
		{"fortifications" "heavy_mg_mg34"}
		{"fortifications" "heavy_mg_maxim"}
		{"fortifications" "heavy_mg_maxim_m1910_30"}
		
		{"fortifications" "placement_nest"}
		{"fortifications" "pillbox_earth"}
		{"fortifications" "watch_tower"}
		{"fortifications" "sandbag_watchtower"}

		{"fortifications" "mortar_pit"}
		{"fortifications" "trench_modular"}	
		{"fortifications" "sandbag_heap_curved"}		
		{"fortifications" "sandbag_framed_straight_mod"}
		{"fortifications" "sandbag_framed_curved"}
		{"fortifications" "bush_cover"}
		
;/* - Fortification_Cover_Skills end - */	
;================Emplacement_cover================	
;================Emplacement_Building================		
;/* - Fortification_Building_Skills begin - */	
		
		{"fortifications" "fin_tower_maxim"}
		{"fortifications" "fin_40mm_itk38b_emplacement"}
		{"fortifications" "fin_76mm_k36_emplacement"}
		{"fortifications" "fin_76mm_m1927_emplacement"}
		{"fortifications" "fin_81mm_krh36_mortar_position"}

;/* - Fortification_Building_Skills EnD - */	
;================Emplacement_Building================
;================Emplacement_Vehicle================
;/* - Fortification_Vehicle_Skills begin - */	
		{"fortifications" "fin_emplacement_watch_tower"}
		{"fortifications" "fin_emplacement_maxim"}		
		{"fortifications" "fin_emplacement_concrete_bunker_ds39"}	
		
		{"fortifications" "fin_emplacement_20mm_itk35"}		
		{"fortifications" "fin_emplacement_20mm_itk40"}			
		{"fortifications" "fin_emplacement_40mm_itk38b"}		
		{"fortifications" "fin_emplacement_75mm_itk37"}
		
		{"fortifications" "fin_emplacement_50mm_krh38"}		
		{"fortifications" "fin_emplacement_81mm_krh36"}		
		{"fortifications" "fin_emplacement_120mm_krh40"}			
		{"fortifications" "fin_emplacement_170mm_minewerfer"}
		
		{"fortifications" "fin_emplacement_37mm_pstk36"}	
		{"fortifications" "fin_emplacement_75mm_k40"}		
		{"fortifications" "fin_emplacement_75mm_k44"}		
		{"fortifications" "fin_emplacement_76mm_k36"}	
		
		{"fortifications" "fin_emplacement_76mm_m1927_fin"}		
		{"fortifications" "fin_emplacement_84mm_k18"}
		{"fortifications" "fin_emplacement_107mm_k10"}		
		{"fortifications" "fin_emplacement_120mm_k78_31"}		
		
;/* - Fortification_Vehicle_Skills EnD - */	
;================Emplacement_Vehicle================	

	}
	{"resources" "1000%"}
	{"resources_regeneration" "50%"}
	{mechanic factor 10.0}
)
	
;=============================================================;/* - Fortification_engineer_fin_Skills EnD - */=============================================================================
;=============================================================;/* - Fortification_engineer_heavy_fin_Skills begin - */=============================================================================

;================Emplacement_cover================
;/* - Fortification_Cover_Skills begin - */	
(define "engineer_heavy_fin"
	{fortification}
	{barricade
		{"fortifications" "barricade_sq"}
		{"fortifications" "barricade"}
		{"fortifications" "barbwire"}
		{"fortifications" "hedgehog"}
		{"fortifications" "foxhole_big"}
		{"fortifications" "tank_cover"}
	
		{"fortifications" "heavy_mg_mg34"}
		{"fortifications" "heavy_mg_maxim"}
		{"fortifications" "heavy_mg_maxim_m1910_30"}
		
		{"fortifications" "placement_nest"}
		{"fortifications" "pillbox_earth"}
		{"fortifications" "watch_tower"}
		{"fortifications" "sandbag_watchtower"}

		{"fortifications" "mortar_pit"}
		{"fortifications" "trench_modular"}	
		{"fortifications" "sandbag_heap_curved"}		
		{"fortifications" "sandbag_framed_straight_mod"}
		{"fortifications" "sandbag_framed_curved"}
		{"fortifications" "bush_cover"}	


;/* - Fortification_Cover_Skills end - */	
;================Emplacement_cover================	
;================Emplacement_Building================		
;/* - Fortification_Building_Skills begin - */	

		{"fortifications" "emplacement_small_deep_mg"}
		{"fortifications" "watch_tower"}
		{"fortifications" "mortar_pit"}
		{"fortifications" "mortar_pit_heavy"}
		{"fortifications" "emplacement_light_aa_mg"}
		{"fortifications" "emplacement_light_aa"}
		{"fortifications" "emplacement_middle_aa_heavy"}
		{"fortifications" "emplacement_middle_at"}
		{"fortifications" "emplacement_middle_fieldgun"}
		{"fortifications" "emplacement_middle_howitzer"}
		
		{"fortifications" "fin_bunker"}
		{"fortifications" "fin_75mm_k44_emplacement"}	
		{"fortifications" "fin_coastal_gun"}	

;/* - Fortification_Building_Skills EnD - */	
;================Emplacement_Building================
;================Emplacement_Vehicle================
;/* - Fortification_Vehicle_Skills begin - */		
		{"fortifications" "fin_emplacement_watch_tower"}
		{"fortifications" "fin_emplacement_maxim"}		
		{"fortifications" "fin_emplacement_concrete_bunker_ds39"}	
		
		{"fortifications" "fin_emplacement_20mm_itk35"}		
		{"fortifications" "fin_emplacement_20mm_itk40"}			
		{"fortifications" "fin_emplacement_40mm_itk38b"}		
		{"fortifications" "fin_emplacement_75mm_itk37"}
		
		{"fortifications" "fin_emplacement_50mm_krh38"}		
		{"fortifications" "fin_emplacement_81mm_krh36"}		
		{"fortifications" "fin_emplacement_120mm_krh40"}			
		{"fortifications" "fin_emplacement_170mm_minewerfer"}
		
		{"fortifications" "fin_emplacement_37mm_pstk36"}	
		{"fortifications" "fin_emplacement_75mm_k40"}		
		{"fortifications" "fin_emplacement_75mm_k44"}		
		{"fortifications" "fin_emplacement_76mm_k36"}	
		
		{"fortifications" "fin_emplacement_76mm_m1927_fin"}		
		{"fortifications" "fin_emplacement_84mm_k18"}
		{"fortifications" "fin_emplacement_107mm_k10"}		
		{"fortifications" "fin_emplacement_120mm_k78_31"}	
;/* - Fortification_Vehicle_Skills EnD - */	
;================Emplacement_Vehicle================	

	}
	{"resources" "1000%"}
	{"resources_regeneration" "50%"}
	{mechanic factor 10.0}
)

;=============================================================;/* - Fortification_engineer_heavy_fin_Skills end - */=============================================================================