
; Presets for ger engineer Fortification skills

;/* - Fortification Building Skills - */
;=============================================================light=============================================================================
;/* - Fortification_engineer_light_ger_Skills begin - */
;================Emplacement_cover================
;/* - Fortification_Cover_Skills begin - */		
(define "engineer_light_ger"
	{fortification}
	{barricade
		{"fortifications" "barricade_sq"}
		{"fortifications" "barricade"}
		{"fortifications" "barbwire"}
		{"fortifications" "hedgehog"}
		{"fortifications" "foxhole_big"}
		{"fortifications" "tank_cover"}
	
		{"fortifications" "heavy_mg_mg34"}
		{"fortifications" "heavy_mg_maxim"}
	
		{"fortifications" "placement_nest"}
		{"fortifications" "pillbox_earth"}
		{"fortifications" "watch_tower"}
		{"fortifications" "sandbag_watchtower"}

		{"fortifications" "mortar_pit"}
		{"fortifications" "trench_modular"}	
		{"fortifications" "sandbag_heap_curved"}		
		{"fortifications" "sandbag_framed_straight_mod"}
		{"fortifications" "sandbag_framed_curved"}
		{"fortifications" "bush_cover"}
		

;/* - Fortification_Cover_Skills end - */	
;================Emplacement_cover================
;================Emplacement_Building================
;/* - Fortification_Building_Skills begin - */	

		{"fortifications" "ger_mg34_foxhole"}
		{"fortifications" "ger_mg42_foxhole"}
		{"fortifications" "ger_20mm_flak38_emplacement"}		
		{"fortifications" "ger_37mm_pak36_emplacement"}
		{"fortifications" "ger_75mm_lg40_foxhole"}		
		

;/* - Fortification_Building_Skills EnD - */	
;================Emplacement_Building================
;================Emplacement_Vehicle================	
;/* - Fortification_Vehicle_Skills begin - */
	
		{"fortifications" "ger_emplacement_bunker_osttruppen"}

		{"fortifications" "ger_emplacement_watch_tower_mg34"}
		{"fortifications" "ger_emplacement_watch_tower_mg42"}
		{"fortifications" "ger_emplacement_20mm_flak38"}
		{"fortifications" "ger_emplacement_37mm_pak36"}
		{"fortifications" "ger_emplacement_75mm_lg40"}
		
;/* - Fortification_Vehicle_Skills EnD - */	
;================Emplacement_Vehicle================
	}
	{"resources" "1000%"}
	{"resources_regeneration" "50%"}
	{mechanic factor 10.0}
)
;/* - Fortification_engineer_light_ger_Skills end - */	
;=============================================================middle=============================================================================
;/* - Fortification_engineer_ger_Skills begin - */	
;================Emplacement_cover================
;/* - Fortification_Cover_Skills begin - */	
(define "engineer_ger"
	{fortification}
	{barricade
		{"fortifications" "barricade_sq"}
		{"fortifications" "barricade"}
		{"fortifications" "barbwire"}
		{"fortifications" "hedgehog"}
		{"fortifications" "foxhole_big"}
		{"fortifications" "tank_cover"}
	
		{"fortifications" "heavy_mg_mg34"}
		{"fortifications" "heavy_mg_maxim"}
	
		{"fortifications" "placement_nest"}
		{"fortifications" "pillbox_earth"}
		{"fortifications" "watch_tower"}
		{"fortifications" "sandbag_watchtower"}

		{"fortifications" "mortar_pit"}
		{"fortifications" "trench_modular"}	
		{"fortifications" "sandbag_heap_curved"}		
		{"fortifications" "sandbag_framed_straight_mod"}
		{"fortifications" "sandbag_framed_curved"}
		{"fortifications" "bush_cover"}
		
;/* - Fortification_Cover_Skills end - */	
;================Emplacement_cover================	
;================Emplacement_Building================		
;/* - Fortification_Building_Skills begin - */	

		{"fortifications" "ger_tower_mg34"}
		{"fortifications" "ger_tower_mg42"}
		{"fortifications" "ger_37mm_flak37_emplacement"}
		{"fortifications" "ger_50mm_pak38_emplacement"}
		{"fortifications" "ger_75mm_leig18_emplacement"}	
		{"fortifications" "ger_80mm_sgrw34_mortar_position"}		
		
;/* - Fortification_Building_Skills EnD - */	
;================Emplacement_Building================
;================Emplacement_Vehicle================
;/* - Fortification_Vehicle_Skills begin - */	
		{"fortifications" "ger_emplacement_mg34"}
		{"fortifications" "ger_emplacement_mg42"}
		{"fortifications" "ger_emplacement_concrete_bunker_mg34"}
		{"fortifications" "ger_emplacement_concrete_bunker_mg42"}
		{"fortifications" "ger_emplacement_watch_tower_mg34"}
		{"fortifications" "ger_emplacement_watch_tower_mg42"}
		
		{"fortifications" "ger_emplacement_20mm_flak38"}
		{"fortifications" "ger_emplacement_37mm_flak37"}		
		{"fortifications" "ger_emplacement_concrete_88mm_flak36"}	
		
		{"fortifications" "ger_emplacement_37mm_pak36"}
		{"fortifications" "ger_emplacement_50mm_pak38"}
		{"fortifications" "ger_emplacement_75mm_pak40"}
		{"fortifications" "ger_emplacement_88mm_pak43"}	
		
		{"fortifications" "ger_emplacement_80mm_sgrw34"}
		{"fortifications" "ger_emplacement_100mm_nbw35"}
		{"fortifications" "ger_emplacement_120mm_sgrw42"}		

		{"fortifications" "ger_emplacement_75mm_lg40"}		
		{"fortifications" "ger_emplacement_75mm_leig18"}
		{"fortifications" "ger_emplacement_150mm_sig33"}
		
		{"fortifications" "ger_emplacement_105mm_lefh18"}	
		
		{"fortifications" "ger_emplacement_bunker_osttruppen"}
		{"fortifications" "ger_emplacement_bunker_osttruppen_unlimited"}
;/* - Fortification_Vehicle_Skills EnD - */	
;================Emplacement_Vehicle================	

	}
	{"resources" "1000%"}
	{"resources_regeneration" "50%"}
	{mechanic factor 10.0}
)
;/* - Fortification_engineer_ger_Skills EnD - */	
;=============================================================heavy=============================================================================
;/* - Fortification_engineer_heavy_ger_Skills begin - */
;================Emplacement_cover================
;/* - Fortification_Cover_Skills begin - */	
(define "engineer_heavy_ger"
	{fortification}
	{barricade
		{"fortifications" "barricade_sq"}
		{"fortifications" "barricade"}
		{"fortifications" "barbwire"}
		{"fortifications" "hedgehog"}
		{"fortifications" "foxhole_big"}
		{"fortifications" "tank_cover"}
	
		{"fortifications" "heavy_mg_mg34"}
		{"fortifications" "heavy_mg_maxim"}
	
		{"fortifications" "placement_nest"}
		{"fortifications" "pillbox_earth"}
		{"fortifications" "watch_tower"}
		{"fortifications" "sandbag_watchtower"}

		{"fortifications" "mortar_pit"}
		{"fortifications" "trench_modular"}	
		{"fortifications" "sandbag_heap_curved"}		
		{"fortifications" "sandbag_framed_straight_mod"}
		{"fortifications" "sandbag_framed_curved"}
		{"fortifications" "bush_cover"}	


;/* - Fortification_Cover_Skills end - */	
;================Emplacement_cover================	
;================Emplacement_Building================		
;/* - Fortification_Building_Skills begin - */	

		{"fortifications" "ger_bunker_mg34"}
		{"fortifications" "ger_bunker_mg42"}
		{"fortifications" "ger_bunker_pak40"}
        {"fortifications" "ger_88mm_gun"}
		{"fortifications" "ger_88mm_pak43_emplacement"}
		{"fortifications" "ger_105mm_lefh18_emplacement"}
		{"fortifications" "ger_120mm_sgrw42_emplacement"}		

;/* - Fortification_Building_Skills EnD - */	
;================Emplacement_Building================
;================Emplacement_Vehicle================
;/* - Fortification_Vehicle_Skills begin - */

		{"fortifications" "ger_emplacement_bunker_osttruppen"}
		{"fortifications" "ger_emplacement_bunker_osttruppen_unlimited"}
		{"fortifications" "ger_emplacement_watch_tower_mg34"}
		{"fortifications" "ger_emplacement_watch_tower_mg42"}
		
		{"fortifications" "ger_emplacement_88mm_pak43"}			
		{"fortifications" "ger_emplacement_105mm_lefh18"}		
		{"fortifications" "ger_emplacement_120mm_sgrw42"}
		{"fortifications" "ger_emplacement_150mm_sig33"}

		
;/* - Fortification_Vehicle_Skills EnD - */	
;================Emplacement_Vehicle================	

	}
	{"resources" "1000%"}
	{"resources_regeneration" "50%"}
	{mechanic factor 10.0}
)
;/* - Fortification_engineer_heavy_ger_Skills end - */