{difficulty
	(include "difficulty_generic.inc")
	{any	;// temp to give enemy stats
		{health 1.00}
		{accuracy 1.0}
                {grenade_timeout 0.50}		; modifier on FiringTimeout
		;{burst 1.5}					; multiplier to number of bullets in burst from weapon settings
	}
	{enemy	;// not working in coop
		{health 1.00}
		{accuracy 1.0}
                {grenade_timeout 0.50}		; modifier on FiringTimeout
	}
	{ally
		{health 1.00}
                {accuracy 1.0}
                {grenade_timeout 0.50}		; modifier on FiringTimeout
	}
	{player
		{health 1.00}
                {accuracy 1.0}
                {grenade_timeout 0.50}		; modifier on FiringTimeout
	}
}
