	;Finnish Mod added	
	{"maxim_stand_bunker_fin"
		{vehicle_view "mg_maxim"}
	}
	{"maxim_stand_tower_fin"
		{vehicle_view "mg_maxim"}
	}
	{"maxim_stand_stat_fin"
		{vehicle_view "mg_maxim"}
	}
	{"ds39_stand_stat_fin"
		{vehicle_view "cannon_ds39_stand_fin"}
	}
	{"20mm_itk35_stat"
		{vehicle_view "cannon_20mm_itk35"}
	}
	{"20mm_itk40_stat"
		{vehicle_view "cannon_20mm_itk40"}
	}
	{"20mm_l39_stat"
		{vehicle_view "cannon_20mm_l39"}
	}
	{"20mm_l39_stat_stand"
		{vehicle_view "cannon_20mm_l39"}
	}
	{"37mm_pstk36_stat"
		{vehicle_view "cannon_37mm_pstk36"}
	}
	{"40mm_itk38b_stat"
		{vehicle_view "cannon_40mm_itk38b"}
	}
	{"45mm_pstk32_stat"
		{vehicle_view "cannon_45mm_pstk32"}
	}
	{"47mm_pstk39_stat"
		{vehicle_view "cannon_47mm_pstk39"}
	}
	{"50mm_krh38_stat"
		{vehicle_view "cannon_50mm_krh38"}
	}
	{"50mm_pstk38_stat"
		{vehicle_view "cannon"}
	}
	{"50mm_pstk38_late_stat"
		{vehicle_view "cannon"}
	}
	{"75mm_pstk9738_stat"
		{vehicle_view "cannon_75mm_pstk9738"}
	}
	{"75mm_k40_stat"
		{vehicle_view "cannon_75mm_k40"}
	}
	{"75mm_k44_stat"
		{vehicle_view "cannon_75mm_k44"}
	}
	{"76mm_k02_stat"
		{vehicle_view "cannon_76mm_k02"}
	}
	{"76mm_k02_30_40_stat"
		{vehicle_view "cannon_76mm_k02_30_40"}
	}
	{"76mm_m1927_fin_stat"
		{vehicle_view "cannon_76mm_m1927_fin"}
	}
	{"76mm_k36_stat"
		{vehicle_view "cannon_76mm_k36"}
	}
	{"81mm_krh36_stat"
		{vehicle_view "cannon_81mm_krh36"}
	}
	{"84mm_k18_stat"
		{vehicle_view "cannon_84mm_k18"}
	}
	{"84mm_k18_late_stat"
		{vehicle_view "cannon_84mm_k18"}
	}
	{"100mm_nbw35_stat"
		{vehicle_view "mortar_ger"}
	}
	{"105mm_h33_stat"
		{vehicle_view "cannon_105mm_h33"}
	}
	{"105mm_k34_stat"
		{vehicle_view "cannon_105mm_k34"}
	}
	{"105mm_k13_stat"
		{vehicle_view "cannon_105mm_k13"}
	}
	{"107mm_k10_stat"
		{vehicle_view "cannon_105mm_k13"}
	}
	{"120mm_krh40_stat"
		{vehicle_view "cannon_120mm_krh40"}
	}
	{"120mm_k78_31_stat"
		{vehicle_view "cannon_120mm_k78_31"}
	}
	{"122mm_m1910_fin"
		{vehicle_view "cannon_122mm_m1910_fin"}
	}
	{"150mm_rkh41_stat"
		{vehicle_view "cannon_150mm_nebelwerfer41"}
	}
	{"150mm_h40_stat"
		{vehicle_view "cannon_150mm_h40"}
	}
	{"155mm_h17"
		{vehicle_view "cannon_155mm_h17"}
	}
	{"170mm_minewerfer_stat"
		{vehicle_view "cannon_170mm_minewerfer"}
	}
	{"203mm_h17_stat"
		{vehicle_view "cannon_203mm_h17"}
	}
