    ;Ger Mod added		
	{"mg_stat_shielded_tripod_bunker_entrance"
		{vehicle_view "mg_stand"}
	}	
	{"mg34_tripod_stat"
		{vehicle_view "mg_stand"}
	}	
	{"mg34_tripod_stat_shielded"
		{vehicle_view "mg_stand"}
	}	
	{"mg34_tripod_stat_shielded_bunker"
		{vehicle_view "mg_stand"}
	}
	{"mg34_tripod_stat_shielded_bunker_entrance"
		{vehicle_view "mg_stand"}
	}
	{"mg42_stat_shielded"
		{vehicle_view "mg_stand"}
	}
	{"mg42_tripod_stat_shielded_bunker"
		{vehicle_view "mg_stand"}
	}
	{"mg42_tripod_stat_shielded_bunker_entrance"
		{vehicle_view "mg_stand"}
	}
	{"mg42_tripod_stat"
		{vehicle_view "mg_stand"}
	}
	{"mg42_tripod_stat"
		{vehicle_view "mg_stand"}
	}
	{"mg42_tripod_stat_shielded"
		{vehicle_view "mg_stand"}
	}
	
	

	{"20mm_flak30_stat"
		{vehicle_view "cannon_20mm_flak30"}
	}
	{"20mm_flak38_stat"
		{vehicle_view "cannon_20mm_flak38"}
	}
	{"20mm_flakvierling38_stat"
		{vehicle_view "20mm_flakvierling38"}
	}
	{"37mm_flak37_stat"
		{vehicle_view "cannon_37mm_flak37"}
	}
	{"28mm_pzb41_stat"
		{vehicle_view "cannon_28mm_pzb41"}
	}
	{"37mm_pak36_stat"
		{vehicle_view "cannon_pak36"}
	}
	{"37mm_pak36_late_stat"
		{vehicle_view "cannon_pak36"}
	}
	{"47mm_pakt_stat"
		{vehicle_view "cannon_47mm_pakt"}
	}
	{"50mm_pak38_stat"
		{vehicle_view "cannon_50mm_pak38"}
	}
	{"50mm_pak38_late_stat"
		{vehicle_view "cannon_50mm_pak38"}
	}
	{"50mm_flak41_stat"
		{vehicle_view "cannon_50mm_flak41"}
	}
	{"50mm_flak41_bunker"
		{vehicle_view "cannon_50mm_flak41"}
	}
	{"50mm_kwk39_platform_bunker"
		{vehicle_view "50mm_kwk39_platform"}
	}
	{"75mm_lg40_stat"
		{vehicle_view "cannon_75mm_lg40"}
	}
	{"75mm_legebig18_stat"
		{vehicle_view "cannon_75mm_legebig18"}
	}
	{"75mm_legebig18_snow_stat"
		{vehicle_view "cannon_75mm_legebig18_snow"}
	}
	{"75mm_leig18_stat"
		{vehicle_view "cannon_75mm_leig18"}
	}
	{"75mm_pak40_stat"
		{vehicle_view "cannon_75mm_pak40"}
	}
	{"75mm_pak40_stat_bunker"
		{vehicle_view "cannon_75mm_pak40"}
	}
	{"75mm_pak9738_stat"
		{vehicle_view "cannon_75mm_pak9738"}
	}
	{"75mm_pak9738_late_stat"
		{vehicle_view "cannon_75mm_pak9738"}
	}
	{"75mm_fk18_stat"
		{vehicle_view "cannon"}
	}
	{"80mm_sgrw34_stat"
		{vehicle_view "mortar_ger"}
	}
	{"100mm_nbw35_stat"
		{vehicle_view "cannon_100mm_nbw35"}
	}
	{"80mm_sgrw34_rapid_stat"
		{vehicle_view "mortar_ger"}
	}
	{"88mm_flak18_stat"
		{vehicle_view "flak18"}
	}
	{"88mm_flak36_stat"
		{vehicle_view "flak18"}
	}
	{"88mm_pak4341_stat"
		{vehicle_view "cannon_88mm_pak4341"}
	}
	{"88mm_pak4341_emplacement"
		{vehicle_view "cannon_88mm_pak4341"}
	}
	{"105mm_lefh18_stat"
		{vehicle_view "cannon_105mm_lefh18"}
	}
	{"105mm_lefh18m_stat"
		{vehicle_view "cannon"}
	}
	{"105mm_sk18_stat"
		{vehicle_view "cannon_105mm_sk18"}
	}
	{"120mm_sgrw42_stat"
		{vehicle_view "cannon_120mm_sgrw42"}
	}
	{"150mm_nebelwerfer41_stat"
		{vehicle_view "cannon_150mm_nebelwerfer41"}
	}
	{"150mm_sfh18_stat"
		{vehicle_view "cannon_105mm_sk18"}
	}
	{"150mm_sig33_stat"
		{vehicle_view "cannon_sig33"}
	}
	{"150mm_sig33_late_stat"
		{vehicle_view "cannon_sig33"}
	}
	{"170mm_k18_stat"
		{vehicle_view "cannon_170mm_k18"}
	}
	{"200mm_ldgw40_stat"
		{vehicle_view "cannon_200mm_ldgw40"}
	}
	{"210mm_morser18_stat"
		{vehicle_view "cannon_170mm_k18"}
	}
	{"210mm_nebelwerfer42_stat"
		{vehicle_view "cannon_210mm_nebelwerfer42"}
	}
	{"300mm_nebelwerfer42_stat"
		{vehicle_view "cannon_300mm_nebelwerfer42"}
	}
	{"600mm_thor_stat"
		{vehicle_view "thor"}
	}
	{"155mm_gpf_ger_stat"
		{vehicle_view "cannon_155mm_gpf_ger"}
	}
	{"155mm_gpf_platform_stat"
		{vehicle_view "cannon_155mm_gpf_platform"}
	}
	{"sdkfz250a_3_command_vehicle"
		{vehicle_view "sdkfz250_1"}
	}

	;Special Mod added	
	{"150mm_sw34_stat"
		{vehicle_view "special_150mm_sw34"}
	}
	{"ju-52_para_plane_player"
		{vehicle_view "bf110_e2"}
	}
	{"ju-52_para_plane_support"
		{vehicle_view "bf110_e2"}
	}
	{"15mm_mg151_x3_stat"
		;{vehicle_view "cannon_maxim_x4"}
		{vehicle_view "50mm_kwk39_platform"}
	}
	{"15mm_mg151_x3_bunker"
		;{vehicle_view "cannon_maxim_x4"}
		{vehicle_view "50mm_kwk39_platform"}
	}
	{"blitz3_6_prison_vip"
		{vehicle_view "car"}
	}
	{"blitz3_6_prison"
		{vehicle_view "car"}
	}