	;USA Mod added	
	{"m1917_30cal_stat"
		{vehicle_view "m1917_30cal"}
	}
	
	{"m2_30cal_squat_stat"
		{vehicle_view "m2_30cal_tripod"}
	}
	{"m2_30cal_tripod_bunker"
		{vehicle_view "m2_30cal_tripod"}
	}
	{"m2_30cal_tripod_stand_stat"
		{vehicle_view "m2_30cal_tripod"}
	}
	{"m2_30cal_tripod_stat"
		{vehicle_view "m2_30cal_tripod"}
	}

	{"m2_50cal_aa_stat"
		{vehicle_view "m2_50cal_tripod"}
	}	
	{"m2_50cal_tripod_stand_stat"
		{vehicle_view "m2_50cal_tripod"}
	}	
	{"m2_50cal_tripod_bunker"
		{vehicle_view "m2_50cal_tripod"}
	}	
	{"m2_50cal_tripod_squat_stat"
		{vehicle_view "m2_50cal_tripod"}
	}
	{"m2_50cal_tripod_stat"
		{vehicle_view "m2_50cal_tripod"}
	}
	
	{"50cal_quad_m45_stat"
		{vehicle_view "cannon_50cal_quad_m45"}
	}
	{"37mm_m3_stat"
		{vehicle_view "cannon_37mm_m3"}
	}
	{"37mm_m3a1_stat"
		{vehicle_view "cannon_37mm_m3"}
	}
	{"40mm_m1_stat"
		{vehicle_view "cannon_40mm_m1"}
	}
	{"57mm_m1_stat"
		{vehicle_view "cannon_57mm_m1"}
	}
	{"57mm_m1_early_stat"
		{vehicle_view "cannon_57mm_m1"}
	}
	{"57mm_m1_late_stat"
		{vehicle_view "cannon_57mm_m1"}
	}
	{"75mm_m1a1_stat"
		{vehicle_view "cannon_75mm_m1a1"}
	}
	{"75mm_m3a3_stat"
		{vehicle_view "cannon_75mm_m3a3"}
	}
	{"75mm_m1897_stat"
		{vehicle_view "cannon_75mm_m1897"}
	}
	{"76mm_m5_m1_stat"
		{vehicle_view "cannon_76mm_m5_m1"}
	}
	{"76mm_m5_m6_stat"
		{vehicle_view "cannon_76mm_m5_m6"}
	}
	{"81mm_m1_stat"
		{vehicle_view "cannon_81mm_m1"}
	}
	{"81mm_m1_sm_stat"
		{vehicle_view "cannon_81mm_m1"}
	}
	{"60mm_m2_stat"
		{vehicle_view "60mm_m2"}
	}
	{"60mm_m2_late_stat"
		{vehicle_view "60mm_m2"}
	}
	{"105mm_m2a1_stat"
		{vehicle_view "cannon_105mm_m2a1"}
	}
	{"105mm_m3_stat"
		{vehicle_view "cannon_105mm_m3"}
	}
	{"107mm_m2_stat"
		{vehicle_view "cannon_107mm_m2"}
	}
	{"114mm_m1_stat"
		{vehicle_view "cannon_114mm_m1"}
	}
	{"155mm_gpf_us_stat"
		{vehicle_view "cannon_155mm_gpf_us"}
	}
	{"155mm_m1_stat"
		{vehicle_view "cannon_155mm_m1"}
	}
	{"155mm_schneider_us_stat"
		{vehicle_view "cannon_155mm_schneider_us"}
	}
	{"155mm_m1a1_longtom_stat"
		{vehicle_view "cannon_155mm_m1a1_longtom"}
	}
	{"155mm_m1a1_longtom_sm_stat"
		{vehicle_view "cannon_155mm_m1a1_longtom"}
	}
	{"203mm_m1_stat"
		{vehicle_view "cannon_203mm_m1"}
	}
	{"90mm_m1a1_stat"
		{vehicle_view "cannon_90mm_m1a1"}
	}
	{"90mm_m1a1_stat_foxhole"
		{vehicle_view "cannon_90mm_m1a1"}
	}
	{"m3a1_command_vehicle"
		{vehicle_view "m3a1_commander"}
	}
	{"c47_d_para_plane"
		{vehicle_view "c47_d"}
	}
	{"c47_d_para_plane_player"
		{vehicle_view "c47_d"}
	}
	{"stretcher"
		{vehicle_view "usa_stretcher"}
	}