	;Rus Mod added	
	{"maxim_stand_bunker"
		{vehicle_view "mg_maxim"}
	}
	{"maxim_stand_tower"
		{vehicle_view "mg_maxim"}
	}

	{"ds39_stand_bunker"
		{vehicle_view "cannon_ds39_stand"}
	}	
	{"ds39_stand_bunker"
		{vehicle_view "cannon_ds39_stand"}
	}
	{"ds39_stand_stat"
		{vehicle_view "cannon_ds39_stand"}
	}	
	{"ds39_stand_tower"
		{vehicle_view "cannon_ds39_stand"}
	}	
	{"sg43_stand_bunker"
		{vehicle_view "cannon_sg43_stand"}
	}
	{"sg43_stand_stat"
		{vehicle_view "cannon_sg43_stand"}
	}
	{"sg43_stand_tower"
		{vehicle_view "cannon_sg43_stand"}
	}	
	{"dshk_stat"
		{vehicle_view "mg_dshk"}
	}
	{"dshk_aa_stat"
		{vehicle_view "cannon_dshk_aa"}
	}	
	{"sg43_stand_stat"
		{vehicle_view "cannon_sg43_stand"}
	}

	{"ds39_stand_stat"
		{vehicle_view "cannon_ds39_stand"}
	}
	{"dshk_aa_stat"
		{vehicle_view "cannon_dshk_aa"}
	}
	{"dshk_stan_stat"
		{vehicle_view "mg_dshk"}
	}
	{"browning_m2_tower"
		{vehicle_view "m2_50cal_tripod"}
	}	
	{"25mm_72k_stat"
		{vehicle_view "cannon_25mm_72k"}
	}
	{"37mm_61k_stat"
		{vehicle_view "cannon_37mm_61k"}
	}
	{"37mm_m30_stat"
		{vehicle_view "cannon_pak36"}
	}
	{"45mm_m37_stat"
		{vehicle_view "cannon_m37"}
	}
	{"45mm_m42_stat"
		{vehicle_view "cannon_m37"}
	}
	{"57mm_zis2_stat"
		{vehicle_view "cannon"}
	}
	{"57mm_zis2_late_stat"
		{vehicle_view "cannon"}
	}
	{"76mm_m1902_stat"
		{vehicle_view "cannon_76mm_m1902"}
	}
	{"76mm_bpk76_stat"
		{vehicle_view "cannon_76mm_bpk76"}
	}
	{"76mm_m1927_stat"
		{vehicle_view "cannon_76mm_m1927"}
	}
	{"76mm_m1927_late_stat"
		{vehicle_view "cannon_76mm_m1927"}
	}
	{"76mm_m43_stat"
		{vehicle_view "cannon_76mm_m43"}
	}
	{"76mm_m1933_stat"
		{vehicle_view "cannon_76mm_m1933"}
	}
	{"76mm_m1938_stat"
		{vehicle_view "52k"}
	}
	{"76mm_f22_stat"
		{vehicle_view "cannon_76mm_f22"}
	}
	{"76mm_zis3_stat"
		{vehicle_view "cannon_76mm_zis3"}
	}
	{"82mm_bm37_stat"
		{vehicle_view "mortar_rus"}
	}
	{"85mm_52k_stat"
		{vehicle_view "52k"}
	}
	{"100mm_bs3_stat"
		{vehicle_view "cannon_100mm_bs3"}
	}
	{"107mm_m1910_30_stat"
		{vehicle_view "cannon_107mm_m1910_30"}
	}
	{"122mm_a19_stat"
		{vehicle_view "cannon_122mm_a19"}
	}
	{"122mm_m1910_stat"
		{vehicle_view "cannon_122mm_m1910"}
	}
	{"122mm_m30_stat"
		{vehicle_view "cannon_122mm_m30"}
	}
	{"152mm_ml20_stat"
		{vehicle_view "cannon_152mm_ml20"}
	}
	{"152mm_br2_stat"
		{vehicle_view "b4"}
	}
	{"203mm_b4_stat"
		{vehicle_view "b4"}
	}
	{"280mm_br5_stat"
		{vehicle_view "b4"}
	}
	{"120mm_pm38_stat"
		{vehicle_view "cannon_120mm_pm38"}
	}
	{"m41_ampulomet_stat"
		{vehicle_view "m41_ampulomet"}
	}
	{"305mm_mb_2_12_stat"
		{vehicle_view "cannon_305mm_mb_2_12"}
	}
	{"300mm_m31_stat"
		{vehicle_view "300mm_m31"}
	}
	{"300mm_m30_stat"
		{vehicle_view "300mm_m30"}
	}
	
	{"ba20_command_vehicle"
		{vehicle_view "ba20"}
	}